# Generated by Django 5.1 on 2026-02-02 08:00

from decimal import Decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('BILLS', 'Bills & Utilities'), ('HEALTH', 'Healthcare'), ('EDUCATION', 'Education'), ('INVESTMENT', 'Investment'), ('SALARY', 'Salary'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [
                    models.Index(fields=['-date', 'user'], name='transaction_date_user_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
